// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yequfqzxjhfvuelluzzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllcXVmcXp4amhmdnVlbGx1enpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzE4MTIsImV4cCI6MjA3MjU0NzgxMn0.VqghzVZL4xXbmUvp5MFqNBlPgEw38SOWJ3TIh9B8a9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});